Add functions and gRPC server
ansys/allie-flowkit pull request #12
Opened 2024-05-16 14:00 UTC by FelixKuhnAnsys

- added config
- added dockerfile
- populated externalfunctions (including slight changes to the functions; i.e. removal of session context)
- added functiondefinitions to fill internalstates available functions on launch
- added grpc protos file and generate grpcdefinition
- added grpc server to expose three function: listFunctions, runFunction, streamFunction
- added internalstates

2024-05-17 02:36 UTC, RobPasMue requested changes
I've got some concerns here, mostly with the proto files. We shouldn't be committing the autogenerated code. We should be generating it on the fly when building the library.

Also, it seems like the docstrings are not being build into the docs. We need to modify the docs/api section to include the new sections

2024-05-17 02:36 UTC, RobPasMue commented on pkg/grpcdefinition/externalfunctions.pb.go
These files should not be committed. They should be generated as part of the build process.

2024-05-17 02:36 UTC, RobPasMue commented on pkg/grpcdefinition/externalfunctions_grpc.pb.go
These files should not be committed. They should be generated as part of the build process.

2024-05-17 02:36 UTC, RobPasMue commented on pkg/protos/externalfunctions.proto
I would recommend to add protofile docstrings here

2024-05-17 02:36 UTC, RobPasMue commented on pkg/protos/externalfunctions.proto
> +    rpc ListFunctions(ListFunctionsRequest) returns (ListOfFunctions) {}
```suggestion
    rpc ListFunctions(ListFunctionsRequest) returns (ListFunctionsResponse) {}
```

2024-05-17 02:36 UTC, RobPasMue commented on pkg/protos/externalfunctions.proto
> +message ListOfFunctions {
```suggestion
message ListFunctionsResponse {
```

2024-05-17 06:48 UTC, FelixKuhnAnsys commented on pkg/grpcdefinition/externalfunctions.pb.go
as discussed with andreas for now we leave it and change this at a later point

2024-05-17 06:48 UTC, FelixKuhnAnsys commented on pkg/grpcdefinition/externalfunctions_grpc.pb.go
as discussed with andreas for now we leave it and change this at a later point

2024-05-17 07:09 UTC, FelixKuhnAnsys commented
> I've got some concerns here, mostly with the proto files. We shouldn't be committing the autogenerated code. We should be generating it on the fly when building the library.
> 
> Also, it seems like the docstrings are not being build into the docs. We need to modify the docs/api section to include the new sections

maybe we can move the whole grpc definition to sharedtypes at a later point? otherwise we would need another public repo for it. for now andreas said to keep it here do to time constraints.

not sure where/how to modify the docs/api, maybe we can do it together on monday and you can show me? i think this can be done in a seperate pr though

2024-05-17 07:18 UTC, FelixKuhnAnsys commented on pkg/protos/externalfunctions.proto
> +    rpc ListFunctions(ListFunctionsRequest) returns (ListOfFunctions) {}
done

2024-05-17 07:18 UTC, FelixKuhnAnsys commented on pkg/protos/externalfunctions.proto
done

2024-05-17 07:18 UTC, FelixKuhnAnsys commented on pkg/protos/externalfunctions.proto
> +message ListOfFunctions {
done

2024-05-19 23:54 UTC, RobPasMue approved these changes

2024-05-19 23:55 UTC, merged