removed release from ci_cd.yml and added upload_docs_release to relea…
ansys/allie-flowkit pull request #17
Opened 2024-05-21 11:35 UTC by FelixKuhnAnsys

…se.yml

2024-05-21 12:23 UTC, RobPasMue requested changes

2024-05-21 12:23 UTC, RobPasMue commented on .github/workflows/ci_cd.yml
> -  build:
Why are we removing the build? This should be tested on CI/CD

2024-05-27 09:35 UTC, sleeper3000 commented on .github/workflows/ci_cd.yml
> -  build:
fair point, i've put it back in.

2024-05-27 10:17 UTC, RobPasMue approved these changes

2024-05-27 10:19 UTC, merged