feat: add dataextraction functions
ansys/allie-flowkit pull request #47
Opened 2024-08-01 07:44 UTC by laurasgkadri98

2024-08-01 07:48 UTC, RobPasMue approved these changes
Too many lines of code for reviewing easily. I would recommend we start doing smaller PRs for the sake of the reviewers... I just skimmed through the content - LGTM

2024-08-01 07:48 UTC, RobPasMue commented on configs/config.yaml
> +PYFLOWKIT_API_KEY: "flowkit-python-api-key"
Shouldn't it be FLOWKIT_PYTHON rather than PYFLOWKIT?

2024-08-01 08:36 UTC, RobPasMue commented on pkg/externalfunctions/dataextraction.go
> +	// Retrieve the specified branch's SHA (commit hash) from the GitHub repository. This is used to identify the latest state of the branch.
```suggestion
	// Retrieve the specified branch SHA (commit hash) from the GitHub repository. This is used to identify the latest state of the branch.
```

Try committing this change... fingers crossed

2024-08-02 05:57 UTC, RobPasMue requested changes
These changes are not working @Revathyvenugopal162 - the artifact does not contain the information now...

2024-08-08 06:29 UTC, FelixKuhnAnsys approved these changes

2024-08-08 06:30 UTC, merged